### ISSUE TITLE
Trouble with "yarn install" when using "node v12.3.1" and "npm 6.9.0"

### ISSUE THREAD

**Issue by fy2** [nilshartmann/graphql-project-example#1]
Thanks a lot for this demo code.

I have managed to get it to run on "node v10.15.3" and "npm 6.4.1" after several unsuccessful attempts with the latest versions of those two (12.3.1" and "6.9.0" respectively).

`yarn install
yarn install v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[###----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 380/2872[4/4] 🔨  Building fresh packages...
[-/3] ⠁ waiting...
[2/3] ⠁ fsevents
warning Error running install script for optional dependency: "/Users/f.yalcin/sandbox/ix/graphql-project-example/frontend/node_modules/chokidar/node_modules/fsevents: Command failed.
Exit code: 1
`
(...)
`
../fsevents.cc:43:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> exports);
                           ~~~~^
../fsevents.cc:43:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> exports);
                           ~~~~^
In file included from ../fsevents.cc:73:
../src/constants.cc:89:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagNone\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagNone));
          ^
`

**Comment by nilshartmann** [comment]
Thanks for your hint! 

For now I will add a note to the `README` file to point out that node v10 is required to run the example.

If you have any ideas why node 12/npm 6.9 does not work (guess it's more node related, not npm-related problem), please let me know (currently no time to figure it out myself 😢)

**Comment by fy2** [comment]
I will say for now the fix is to downgrade Node...

Unfortunately I am relatively new to this (part of the reason why ended up here), so please don't get your hopes up for a fix with Node 12 from me ;-)

Thanks for the well written article in iX June - 2019!
